export const locais = [
    {
        id: 1,
        nome: "Praia de Boa Viagem",
        endereco: "Av. Boa Viagem, Boa Viagem, Recife - PE, 51011-000",
        latitude: -8.114217,
        longitude: -34.903281,
        descricao: "Praia famosa com águas mornas, recifes naturais e grande calçadão para lazer.",
        comoChegar: "https://www.google.com/maps?q=-8.114217,-34.903281",
    },
    {
        id: 2,
        nome: "Instituto Ricardo Brennand",
        endereco: "Alameda Antônio Brennand, Várzea, Recife - PE, 50741-904",
        latitude: -8.047562,
        longitude: -34.978162,
        descricao: "Museu com vasto acervo cultural, incluindo armas medievais e arte.",
        comoChegar: "https://www.google.com/maps?q=-8.047562,-34.978162",
    },
    {
        id: 3,
        nome: "Paço do Frevo",
        endereco: "Praça do Arsenal da Marinha, Recife Antigo, Recife - PE, 50030-360",
        latitude: -8.062017,
        longitude: -34.871080,
        descricao: "Espaço cultural dedicado ao frevo, música e dança tradicional de Pernambuco.",
        comoChegar: "https://www.google.com/maps?q=-8.062017,-34.871080",
    },
    {
        id: 4,
        nome: "Shopping RioMar",
        endereco: "Av. República do Líbano, 2510, Pina, Recife - PE, 51110-160",
        latitude: -8.084913,
        longitude: -34.894073,
        descricao: "Centro de compras e lazer com lojas, restaurantes e cinema.",
        comoChegar: "https://www.google.com/maps?q=-8.084913,-34.894073",
    },
    {
        id: 5,
        nome: "Shopping Recife",
        endereco: "R. Padre Carapuceiro, 777, Boa Viagem, Recife - PE, 51020-280",
        latitude: -8.112005,
        longitude: -34.894401,
        descricao: "Grande shopping center com várias lojas, praça de alimentação e eventos.",
        comoChegar: "https://www.google.com/maps?q=-8.112005,-34.894401",
    },
    {
        id: 6,
        nome: "Marco Zero",
        endereco: "Praça Rio Branco, Recife Antigo, Recife - PE, 50030-310",
        latitude: -8.063173,
        longitude: -34.871140,
        descricao: "Ponto central do Recife com vista para o mar e esculturas famosas.",
        comoChegar: "https://www.google.com/maps?q=-8.063173,-34.871140",
    },
    {
        id: 7,
        nome: "Parque da Jaqueira",
        endereco: "R. do Futuro, 959, Graças, Recife - PE, 52050-010",
        latitude: -8.039784,
        longitude: -34.898899,
        descricao: "Parque urbano popular para atividades ao ar livre, como caminhadas e piqueniques.",
        comoChegar: "https://www.google.com/maps?q=-8.039784,-34.898899",
    },
{ id: 8, name: 'Museu Cais do Sertão', description: 'Museu interativo que celebra a cultura sertaneja.', address: 'Av. Alfredo Lisboa, Recife Antigo, Recife - PE, 50030-150', latitude: -8.062506, longitude: -34.870977, category: 'Museu', image: require('./assets/cais-do-sertao.png') },
  { id: 9, name: 'Casa da Cultura', description: 'Antiga prisão transformada em centro cultural.', address: 'R. Floriano Peixoto, São José, Recife - PE, 50020-060', latitude: -8.065624, longitude: -34.877051, category: 'Histórico', image: require('./assets/casa-da-cultura.png') },
  { id: 10, name: 'Jardim Botânico do Recife', description: 'Espaço verde para educação ambiental e lazer.', address: 'BR-101, Curado, Recife - PE, 50791-540', latitude: -8.072165, longitude: -34.982872, category: 'Natureza', image: require('./assets/jardim-botanico.png') },
  { id: 11, name: 'Parque Dona Lindu', description: 'Parque cultural projetado por Niemeyer.', address: 'Av. Boa Viagem, Boa Viagem, Recife - PE, 51030-000', latitude: -8.125587, longitude: -34.900826, category: 'Parques', image: require('./assets/parque-dona-lindu.png') },
  { id: 12, name: 'Basílica de Nossa Senhora do Carmo', description: 'Igreja histórica com arquitetura barroca.', address: 'Av. Dantas Barreto, Santo Antônio, Recife - PE, 50020-080', latitude: -8.063994, longitude: -34.876394, category: 'Histórico', image: require('./assets/basilica-do-carmo.png') },
  { id: 13, name: 'Capela Dourada', description: 'Capela com impressionantes talhas em ouro.', address: 'R. do Imperador Dom Pedro II, Santo Antônio, Recife - PE, 50010-240', latitude: -8.064856, longitude: -34.876633, category: 'Histórico', image: require('./assets/capela-dourada.png') },
  { id: 14, name: 'Parque de Santana', description: 'Parque para esportes e lazer, com quadras e ciclovias.', address: 'Rua Jorge Gomes, Santana, Recife - PE, 52060-500', latitude: -8.025661, longitude: -34.905847, category: 'Parques', image: require('./assets/parque-de-santana.png') },
  { id: 15, name: 'Mercado de São José', description: 'Mercado tradicional com artesanato e comidas típicas.', address: 'Praça Dom Vital, São José, Recife - PE, 50020-540', latitude: -8.066934, longitude: -34.877238, category: 'Histórico', image: require('./assets/mercado-de-sao-jose.png') },
  { id: 16, name: 'Praia do Pina', description: 'Praia urbana próxima ao centro do Recife.', address: 'Av. Boa Viagem, Pina, Recife - PE, 51011-000', latitude: -8.083435, longitude: -34.899484, category: 'Praia', image: require('./assets/praia-do-pina.png') },
  { id: 17, name: 'Igreja Madre de Deus', description: 'Igreja barroca do século XVII.', address: 'R. Madre de Deus, Recife Antigo, Recife - PE, 50030-070', latitude: -8.063418, longitude: -34.871808, category: 'Histórico', image: require('./assets/igreja-madre-de-deus.png') },
  { id: 18, name: 'Rua do Bom Jesus', description: 'Rua icônica com sinagogas e edifícios coloridos.', address: 'Recife Antigo, Recife - PE, 50030-090', latitude: -8.062732, longitude: -34.871153, category: 'Histórico', image: require('./assets/rua-do-bom-jesus.png') },
  { id: 19, name: 'Forte das Cinco Pontas', description: 'Fortaleza histórica com museu sobre o Recife.', address: 'Praça das Cinco Pontas, São José, Recife - PE, 50020-100', latitude: -8.075064, longitude: -34.876013, category: 'Histórico', image: require('./assets/forte-cinco-pontas.png') },
  { id: 20, name: 'Praça do Arsenal', description: 'Praça no Recife Antigo com bares e eventos.', address: 'Recife Antigo, Recife - PE, 50030-360', latitude: -8.061768, longitude: -34.871584, category: 'Histórico', image: require('./assets/praca-do-arsenal.png') },
  { id: 21, name: 'Torre Malakoff', description: 'Antigo observatório astronômico.', address: 'Praça do Arsenal, Recife Antigo, Recife - PE, 50030-360', latitude: -8.062589, longitude: -34.870994, category: 'Histórico', image: require('./assets/torre-malakoff.png') },
  { id: 22, name: 'Cinema São Luiz', description: 'Cine-teatro com arquitetura clássica.', address: 'Rua da Aurora, Boa Vista, Recife - PE, 50050-000', latitude: -8.063519, longitude: -34.881037, category: 'Histórico', image: require('./assets/cinema-sao-luiz.png') },
  { id: 23, name: 'Memorial Chico Science', description: 'Homenagem ao líder do Manguebeat.', address: 'Recife Antigo, Recife - PE, 50030-360', latitude: -8.061112, longitude: -34.870960, category: 'Museu', image: require('./assets/memorial-chico-science.png') },
  { id: 24, name: 'Passeio de Catamarã', description: 'Passeio de barco pelos rios do Recife.', address: 'Cais das Cinco Pontas, São José, Recife - PE, 50020-100', latitude: -8.064045, longitude: -34.873789, category: 'Natureza', image: require('./assets/catamara.png') },

];